Revert "lib/timerqueue: Rely on rbtree semantics for next timer"
*This causes a build error as follows:

../drivers/soc/qcom/event_timer.c:54:10: error: 'struct timerqueue_head' has no member named 'head'
   54 |         .head = RB_ROOT,
      |          ^~~~
../drivers/soc/qcom/event_timer.c:55:10: error: 'struct timerqueue_head' has no member named 'next'
   55 |         .next = NULL,
      |          ^~~~

This reverts commit 0135fcb86a0bc9e4484f7e1228cadcc343c5edef.

Signed-off-by: Forenche <prahul2003@gmail.com>